### ISSUE TITLE
Backup to Backblaze fails (Backblaze only supports the 'STANDARD' storage class, and not STANDARD_IA)

### ISSUE THREAD

**Issue by seriousManual** [dral3x/ha-addons#10]
I tried to backup to Backblaze via your addon (thanks for the contribution btw!).

I'm seeing the following error message:
"Backblaze only supports the 'STANDARD' storage class, and not STANDARD_IA"

```
2024-10-22 11:34:35,933 - ThreadPoolExecutor-0_1 - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<Error>\n    <Code>NotImplemented</Code>\n    <Message>Backblaze only supports the \'STANDARD\' storage class, and not STANDARD_IA</Message>\n</Error>\n'
2024-10-22 11:34:35,935 - ThreadPoolExecutor-0_1 - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f8749bfd0>>
2024-10-22 11:34:35,936 - ThreadPoolExecutor-0_1 - botocore.retries.standard - DEBUG - Not retrying request.
2024-10-22 11:34:35,937 - ThreadPoolExecutor-0_1 - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x7f8749ba10>>
2024-10-22 11:34:35,938 - ThreadPoolExecutor-0_1 - botocore.hooks - DEBUG - Event after-call.s3.PutObject: calling handler <function enhance_error_msg at 0x7f8822bc40>
2024-10-22 11:34:35,939 - ThreadPoolExecutor-0_1 - botocore.hooks - DEBUG - Event after-call.s3.PutObject: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7f8749ba90>>
2024-10-22 11:34:35,940 - ThreadPoolExecutor-0_1 - s3transfer.tasks - DEBUG - Exception raised.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/awscli/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/awscli/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/awscli/s3transfer/upload.py", line 758, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/usr/lib/python3.11/site-packages/awscli/botocore/client.py", line 342, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/awscli/botocore/client.py", line 701, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (NotImplemented) when calling the PutObject operation: Backblaze only supports the 'STANDARD' storage class, and not STANDARD_IA
```

Since I have no clue about the S3 API I don't know how much of a dealbreaker this issue is.
Is backupping to Backblaze possible at all (maybe some configuration that is missing?) or is there no chance?

**Comment by seriousManual** [comment]
Solved, I was not aware that I can explicitely choose the Storage class in the Addon :)

![image](https://github.com/user-attachments/assets/74a6cdf9-a5f5-4f50-b107-43b72cf59894)

**Comment by dral3x** [comment]
@seriousManual yes, the storage class is configurable. I was not aware that `STANDARD_IA` was not supported on other cloud services. Thanks for letting me know, and thanks for using this addon 👍
